# Generated by Django 3.1.12 on 2021-12-13 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='communitycode',
            new_name='postcode',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='customercode',
            new_name='referral_code',
        ),
        migrations.RemoveField(
            model_name='users',
            name='salescode',
        ),
    ]
