# Generated by Django 3.1.12 on 2021-12-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='session_id',
            new_name='session',
        ),
    ]
