# Generated by Django 3.1.12 on 2022-01-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='postcode',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='employee',
            name='referral',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='employee',
            name='referral_code',
            field=models.TextField(max_length=150),
        ),
    ]
