# Generated by Django 3.1.12 on 2021-12-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_business_details_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_details',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
