# Generated by Django 3.1.12 on 2021-12-13 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20211213_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='recommended_by',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserOtp',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
