# Generated by Django 3.1.12 on 2021-12-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_payments_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='user_id',
            new_name='user',
        ),
    ]
