# Generated by Django 3.1.12 on 2021-12-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20211201_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='session',
            field=models.CharField(max_length=200),
        ),
    ]
