# Generated by Django 3.1.12 on 2021-12-01 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20211201_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='session',
            new_name='session_id',
        ),
    ]
