# Generated by Django 3.1.12 on 2021-12-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_business_details_add_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default=' ', max_length=150),
            preserve_default=False,
        ),
    ]
