# Generated by Django 3.1.12 on 2021-12-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_business_details_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_details',
            name='name',
        ),
    ]
