# Generated by Django 3.1.12 on 2021-12-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_deals'),
    ]

    operations = [
        migrations.CreateModel(
            name='rewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('targeted_amount', models.CharField(max_length=500)),
                ('referral_member', models.CharField(max_length=500)),
            ],
        ),
    ]
