# Generated by Django 3.1.12 on 2021-12-13 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
