# Generated by Django 3.1.12 on 2021-12-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20211203_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='customer_name',
            new_name='Customer',
        ),
    ]
