# Generated by Django 3.1.12 on 2021-12-06 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.business_details'),
        ),
    ]
