# Generated by Django 3.1.12 on 2021-12-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rewards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_details',
            name='irich',
            field=models.CharField(max_length=200),
        ),
    ]
