# Generated by Django 3.1.12 on 2021-12-18 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20211218_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='role',
            new_name='designation',
        ),
    ]
