# Generated by Django 3.1.12 on 2021-12-06 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_payments_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='name',
            new_name='business',
        ),
    ]
