# Generated by Django 3.1.12 on 2021-12-07 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20211206_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_details',
            name='business_code',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payments',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='authentication.business_details'),
        ),
    ]
