# Generated by Django 3.1.12 on 2021-12-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20211207_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_details',
            name='qrcode',
        ),
    ]
