# Generated by Django 3.1.12 on 2021-12-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_remove_business_details_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_details',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode'),
        ),
    ]
