# Generated by Django 3.1.12 on 2021-12-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_remove_business_details_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_details',
            name='qrcode',
            field=models.ImageField(default=' ', upload_to=''),
            preserve_default=False,
        ),
    ]
