# Generated by Django 3.1.12 on 2021-12-08 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_business_details_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_details',
            name='qrcode',
        ),
    ]
