# Generated by Django 3.1.12 on 2021-12-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_remove_business_details_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_details',
            name='qr',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
