# Generated by Django 3.1.12 on 2021-12-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_business_details_qr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_details',
            name='qr',
        ),
        migrations.AddField(
            model_name='business_details',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
