# Generated by Django 3.1.12 on 2021-12-09 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_auto_20211208_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='category',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='genericexpense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='genericexpense',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='category',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='person',
        ),
        migrations.DeleteModel(
            name='Restraunt',
        ),
        migrations.AlterField(
            model_name='payments',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.business_details'),
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='BillCategory',
        ),
        migrations.DeleteModel(
            name='GenericExpense',
        ),
        migrations.DeleteModel(
            name='GenericExpenseCategory',
        ),
        migrations.DeleteModel(
            name='Payroll',
        ),
        migrations.DeleteModel(
            name='PayrollCategory',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
